[package]
name = "min-request"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
min-protocol = { path = "../min-protocol" }
min-identity = { path = "../min-identity" }
min-wire = { path = "../min-wire" }
serde = { version = "1", features = ["derive"] }
min-storage = { path = "../min-storage" }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
